AWSTemplateFormatVersion: "2010-09-09"

Description: >
  This template will deploy compute component

Parameters:
  VpcIdParameter:
    Type: String
  # This parameter displays the sub-networks enabled by aws in specific zones
  SubnetId1Parameter:
    Type: AWS::EC2::Subnet::Id
    Description: "us-east-2a (use2-az1)"
  SubnetId2Parameter:
    Type: AWS::EC2::Subnet::Id
    Description: "us-east-2b (use2-az2)"
  ImageIdParameter:
    Type: String
  KeyNameParameter:
    Type: String
  InstanceTypesParameter:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t3.micro
    Description: You can choose between t2.micro and t3.micro if you don't specify anyone t2.micro will be a instance default


Resources:
  SecurityGroupHtpp:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP connection from all origins
      GroupName: SecurityGroupAlb
      VpcId:
        Ref: VpcIdParameter
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          FromPort: 0
          ToPort: 0
          CidrIp: 0.0.0.0/0

  SecurityGroupHtppSsh:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SHH AND HTTP conection to ASG from All Origin, proximaly just from ALB
      GroupName: SecurityGroupAsg
      VpcId:
        Ref: VpcIdParameter
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          FromPort: 0
          ToPort: 0
          CidrIp: 0.0.0.0/0

  AlbScableApp:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      IpAddressType: ipv4
      Name: Alb-Scable-App
      Scheme: internet-facing
      SecurityGroups: 
        - Ref: SecurityGroupHtpp
      Subnets: 
        - Ref: SubnetId1Parameter
        - Ref: SubnetId2Parameter
      Type: application

  ListenerAlbScableApp:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn:
        Ref: AlbScableApp
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn:
            Ref: TargetGroupAlbScableApp

  TargetGroupAlbScableApp:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      TargetType: instance
      Name: target-group-scable-app
      Protocol: HTTP
      Port: 80
      ProtocolVersion: HTTP1
      IpAddressType: ipv4
      HealthCheckProtocol: HTTP
      VpcId:
        Ref: VpcIdParameter

  
        
      
         

      

